import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eve Music",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-black relative overflow-auto min-h-screen flex flex-col ${inter.className}`}
      >
        {/* Particle Animation */}
        {[...Array(50)].map((_, i) => (
          <div
            key={i}
            className="absolute w-1 h-1 bg-white rounded-full animate-floatUp pointer-events-none z-auto"
            style={{
              left: `${Math.random() * 95}%`,
              top: `${Math.random() * 90}%`,
              animationDelay: `${Math.random() * 2}s`,
              animationDuration: `${Math.random() * 5 + 2}s`,
            }}
          ></div>
        ))}

        {/* Main Content */}
        <div className="flex-grow">{children}</div>

        {/* Footer Image */}
        <section className="absolute bottom-0 left-0 w-full">
          <img
            src="/images/main_footer.png"
            alt="Footer Image"
            className="w-full object-cover"
          />
        </section>
      </body>
    </html>
  );
}
